config/routes.rb
Rails.application.routes.draw do
  devise_for :users , controllers: {
        sessions: 'users/sessions'
      }
   
  

    root to: 'home#index'
    resources :posts

    post 'create_comment' => "posts#create_comment"
    resources :categories
    resources :users

    get 'Art' => "home#art"
    get 'photography' => "home#photography"
    get 'animals' => "home#animals"
    get 'travel' => "home#travel"
    

    mount Resque::Server, :at => "/resque"
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
	 mount_uploader :image, MediaFileUploader
	 has_many :comments
	 belongs_to :user
	 belongs_to :category
end 

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :image, MediaFileUploader
  has_many :posts
  belongs_to :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end



		
		

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :authenticate_user!
	
	def index
	
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
	def index
		@posts = Post.all
	end

	def  art
		@category = Category.where(title: 'Art').last
		@posts = @category.posts
		render 'index'
	end

	def photography
		@category = Category.where(title: 'photography').last
		@posts = @category.posts
		render 'index'
	end
	def animals
		@category = Category.where(title: 'animals').last
		@posts = @category.posts
		render  'index'
	end

	def travel
		@category = Category.where(title: 'travels').last
		@posts = @category.posts
		render  'index'
	end

end 

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!
	layout 'posts'

	def index
	end

	def new
		@post = Post.new
	end
	def create
		@post = Post.new(post_params)
		@post.user_id = current_user.id
		if @post.save
			flash[:notice] = "create sucessfully"
			redirect_to  post_path(@post)
		else
			render 'new'
		end
	end

	def show
		@posts = current_user.posts.includes(:comments)
		# @comments =  @posts.comments
		# @comment = @posts.comments.build
	end

	def edit
		@post = Post.find(params[:id])
	end
	def update
		@post = Post.find(params[:id])
		if  @post.update(post_params)
			flash[:notice] = "update sucessfully"
		 redirect_to  post_path
		else
			render 'edit'
	end
end


def create_comment
	@comment = Comment.new(comment_params)
	@comment.user_id = current_user.id
	@comment.save
	post = @comment.post
	user1 = post.user
	user2 = @comment.user
	Resque.enqueue(Archive, user1.id, user2.id)
	redirect_to post_path(post)
end

def destroy
	@post = Post.find[params[:id]]
	@params.destroy
	flash[:notice] = "Delete successfully"
	redirect_to  post_path
end
	private
	def post_params
		params.require(:post).permit(:title,:description,:user_id, :image, :category_id)
	end
	def comment_params
		params.require(:comment).permit(:post_id, :comment)
	end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def edit
		@user = current_user
	end

	def update
		@user = User.find(params[:id])
		@user.update(user_params)
		flash[:notice] = "user update sucessfully"
		redirect_to  root_path(@user)
	end
	private
		def  user_params
			params.require(:user).permit(:first_name, :last_name, :bio, :facebook_url,:twitter_url, :website_url, :image)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
		:user
	end
	def resource
		@resource ||= current_user
	end
	def device_mapping
		@devise_mapping ||= Devise.mapping[:user]
	end
end

app/views/home/index.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="col-md-8">
 			<% @posts.each do |post| %>
				<div  class="well">
					<% if post.image.present? %>
					<div class="style_image">
						<%= image_tag(post.image.url) %></div>
					<% else %>
					<div class="style_image">
						<%= image_tag('dummy_img.png') %></div>
					<% end %>
						<h1><%=  post.title %></h1><br>
						<p><%= post.description %></p>
				</div>
			<% end %>
		</div>
		<div  class="col-md-4">
		</div>
	</div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= image_tag "logo.png", :style => "background-position: 0 -334px;
      border-radius: 0px;
        width: 200px;
        height: 40px;
        display: inline-block;
        text-indent: -9999px;
        margin-right: 10px;
        margin-top: 0px;" %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!--<li><a href="#">Link <span class="sr-only">(current)</span></a></li>-->
        <li ><%= link_to 'Art',    Art_path(@post), :style => "padding-top: 25px;
    padding-bottom: 15px; 
     color: black; 
   " %></li>
        <li><%= link_to 'Photography', photography_path(@post), :style => "padding-top: 25px;
    padding-bottom: 15px; 
     color: black; 
   "  %></li>
        <li><%= link_to 'Animls', animals_path(@post), :style => "padding-top: 25px;
    padding-bottom: 15px; 
     color: black; 
   " %></li>
        <li><%= link_to 'Travel', travel_path(@post), :style => "padding-top: 25px;
    padding-bottom: 15px; 
     color: black; 
   " %></li>
        <!--<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#"></a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li> -->
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% if user_signed_in? %>
                <li><%= link_to 'New Post', new_post_path(@post) %></li><hr>
                <li><%= link_to 'My Profile', post_path(current_user)  %></li><hr>
                <li><%= link_to 'Edit Profile',  edit_user_path(current_user) %></li> <hr>
                <li><%= link_to 'SignOut', destroy_user_session_path, method: :delete %></li><hr>
            
            <% else %>
            <li><%= link_to 'LogIn', new_user_session_path %></li>
            <li><%= link_to 'New User' %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_posts_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= image_tag "logo.png", :style => "background-position: 0 -334px;
      border-radius: 0px;
        width: 159px;
        height: 39px;
        display: inline-block;
        text-indent: -9999px;
        margin-right: 10px;
        margin-top: 0px;" %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
       
        <!--<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#"></a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li> -->
      </ul>
      <!-- <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
           
          <% if user_signed_in? %>
           <li><%= link_to 'New Post', new_post_path(@post) %></li>
           <li role="separator" class="divider"></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
            <li role="separator" class="divider"></li>
            <% else %>
            <li><%= link_to 'LogIn', new_user_session_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'New User' %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PandaApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body class="body">

<% if params[:action] == 'index' %>
	<%= image_tag "fb.jpg", :style => "display: block;height: 200px;
    width: 1362px;
    margin-left: auto;
    margin-right: auto; border-radius: 0%"  %>

<% elsif params[:action] == 'art' %>
	<%= image_tag "art.jpg", :style => "display: block;height: 200px;
    width: 1362px;
    margin-left: auto;
    margin-right: auto; border-radius: 0%"  %>

<% elsif params[:action] == 'photography' %>
<%= image_tag "photograpy.jpg", :style => "display: block;height: 200px;
    width: 1362px;
    margin-left: auto;
    margin-right: auto; border-radius: 0%"  %>

	<% elsif params[:action] == 'animals' %>
	<%= image_tag "animals.jpg", :style => "display: block;height: 200px;
    width: 1362px;
    margin-left: auto;
    margin-right: auto; border-radius: 0%"  %>

<% elsif params[:action] == 'travel' %>
<%= image_tag "Travels.jpg", :style => "display: block;height: 200px;
    width: 1362px;
    margin-left: auto;
    margin-right: auto; border-radius: 0%"  %>

<% end %>
    
<%= render 'layouts/navigation' %>
 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>
<div  class="container">
<%= yield %>
</div>
</body>
</html>

app/views/layouts/posts.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PandaApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body class="body">
<%= image_tag "fb.jpg", :style => "display: block;height: 200px;
    width: 1362px;
    margin-left: auto;
    margin-right: auto; border-radius: 0%"  %>

<%= render 'layouts/posts_nav' %>
 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>
<div  class="container">
<%= yield %>
</div>
</body>
</html>

app/views/posts/edit.html.erb
<%= form_for @post do |f| %>
	<div class="row">
		<div class="col-xs-12">
			<% if  @post.errors.any? %>
				<ul>
					<% @post.errors.messages.ech do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			<% end %>
		</div>
	</div>
	<div class="form-group">
		<label>Title</label><br>
			<%= f.text_field :title , class:  "form-control", placeholder: "Enter the post name" %><br><br>
	</div>
	<div class="form-group">
		<label>Description</label>
			<%= f.text_area :description,  rows:10, class: "form-control" %>
	</div>

	<%= f.submit %>
<% end %>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
	<div class="row">
		<div class="col-xs-12">
			<% if  @post.errors.any? %>
				<ul>
					<% @post.errors.messages.ech do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			<% end %>
		</div>
	</div>
	<div class="form-group">
		<label>Title</label><br>
			<%= f.text_field :title , class:  "form-control", placeholder: "Enter the post name" %><br><br>
	</div>
	
	<div class="form-group">
		<label>Description</label>
			<%= f.text_area :description,  rows: 10, class: "form-control" %>
	</div>

	<div class="form-group">
		<label>Image</label>
	<%= f.file_field :image %>
	</div>
	<div class="form-group">
		<label>Category</label>
		<%= f.select :category_id, options_for_select(Category.all.map{|category| [category.title, category.id]}), class: "form-control" %>
	</div>
	<%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="col-md-8">
			<div class="well">
				<div class="show-img">
					<%= image_tag(current_user.image.url) %>
				</div>
 					<h1 class="h1">Bhagyashri Rahangdale </h1>
 					<p class="para">Community Member</p>
 					<p class="para1">This lazy panda forgot to write something about itself.</p>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<div class="col-md-8">
			<% if @posts.present? %>
				<% @posts.each do |post| %>
					<div class="well">
						<% if post.image.present? %>
							<div class="style_image">
								<%= image_tag(post.image.url, class: 'img-responsive') %>
							</div>
						<% else %>	
							<div class="style_image">
								<%= image_tag('dummy_img.png') %>
							</div>
						<% end %>
							<h2><%= post.title %></h2><br>
									<%= post.description %>
						<% post.comments.each do |comment| %>
							<div class="well well-white">
								<% next if comment.new_record? %>
									<%= comment.comment %>
							</div>
						<% end %>
						<%= form_for post.comments.build,  url:  create_comment_path do |f| %>
									<%= f.hidden_field :post_id %>
								<div class="form-group">
									<%=  f.text_area :comment, class: 'form-control' %>
								</div>
									<%= f.submit 'Comment', class: 'btn btn-primary' %>
						<% end %>
					</div>
				<% end %>	
			<% else %>
				<h1> Sorry, No posts Yet  </h1>
			<% end %>
		</div>
	</div>
</div>

app/views/users/edit.html.erb
<div class="well">
  
  <h1>Profile Information</h1>
  <div class="row">
    <%= form_for(current_user, as: 'user', url: user_path(current_user)) do |f| %>
      <div class="pull-left image-img">
        <%= image_tag(current_user.image.url)  %></div>
        <%=link_to 'Edit', edit_user_path , :style => "margin: 10px;" %><br>
        <div class="field">
        <%= f.file_field :image %>
        </div>
  </div> 
<br>
<div class="well well_edit">      
    <div class="form-group">
      <%= f.label :first_name %><br />
      <%= f.text_field :first_name, class: 'form-control',autofocus: true %>
    </div>

    <div class="form-group">
      <%= f.label :last_name%><br />
      <%= f.text_field :last_name, class: 'form-control',autofocus: true %>
    </div>

    <div class="form-group">
      <%= f.label :Bio %><br />
      <%= f.text_area :bio, class: 'form-control',autofocus: true %>
    </div>

    <div class="form-group">
      <%= f.label :Facebook_url %><br />
      <%= f.text_field :facebook_url,  class: 'form-control', autocomplete: "off" %>
    </div>
    <div class="form-group">
      <%= f.label :website_url %><br />
      <%= f.text_field :website_url,  class: 'form-control', autocomplete: "off" %>
    </div>
    <div class="form-group">
      <%= f.label :Twitter_url %><br />
      <%= f.text_field :twitter_url,  class: 'form-control', autocomplete: "off" %>
    </div>
    <div class="actions">
      <%= f.submit "update" %>
    </div>
  <% end %>
  </div>
  </div>